apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: opencloud-ingress
  namespace: opencloud
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production  
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  labels:
    app: opencloud
spec:
  ingressClassName: nginx
  tls:
    - secretName: opencloud-ssl
      hosts:
      - opencloud.k8s.cluster-4.de          
  rules:
  - host: "opencloud.k8s.cluster-4.de"
    http:
      paths:
        - pathType: Prefix
          path: "/"
          backend:
            service:
              name: opencloud-service
              port:
                number: 443
