# Default values for codimd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  postgresql:
    auth:
      username: "codimd"
      password: "changeme"
      database: "codimd"

# chart version 12.12.10
#image:
#  registry: docker.io
#  repository: bitnami/postgresql
#  tag: 15.10.0-debian-12-r2
